//! `DiscoveryProof` — verifiable evidence of computational work on a challenge.
//!
//! A proof is submitted by a machine after it finds a candidate result.
//! It carries:
//!   1. The result itself (`output_hash` — SHA-256 of the raw output)
//!   2. A **seal** — proof-of-work stamp over the output, structurally
//!      identical to Bitcoin's mining loop so SHA256 ASICs can compute it
//!   3. Enough metadata for an independent verifier to reproduce the check
//!
//! ## Seal formula
//! ```text
//! seal_preimage = seal_nonce_be8 || output_hash_bytes || chain_scoped_challenge_id_bytes
//! seal_hash     = SHA256(seal_preimage)
//! ```
//! The chain scope in `chain_scoped_challenge_id` (format `"{chain_id}::{…}"`)
//! is what prevents a valid proof on QCB from being replayed on another chain.

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::error::PoCDError;

/// Verifiable evidence that a machine performed computational work on a
/// specific challenge and (optionally) found a result worth submitting.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiscoveryProof {
    /// Unique proof ID — generated by the submitting machine.
    pub proof_id: String,

    /// The challenge this proof is for.  Must match a `DiscoveryChallenge`
    /// that is `Active` on the chain.  The embedded `chain_id` prefix is the
    /// cross-chain replay guard.
    pub challenge_id: String,

    /// ID of the machine that performed the work.  Chain-specific format;
    /// this crate treats it as an opaque string.
    pub machine_id: String,

    /// SHA-256 hash (hex) of the raw output / discovery.
    /// For search challenges: hash of the found candidate.
    /// For simulation challenges: hash of the output data file.
    pub output_hash: String,

    /// SHA-256 hash (hex) of the challenge input / parameter bundle the
    /// machine worked on.  Lets verifiers confirm the machine solved the
    /// right problem instance.
    pub input_hash: String,

    /// IPFS CID or other content-addressable reference to the methodology /
    /// algorithm description.  Must be published before reward claims are
    /// accepted for tracks that require methodology disclosure.
    pub methodology_ref: String,

    /// Domain-specific nonce or search parameter (e.g., the candidate value
    /// found for a discrete-log challenge).
    pub discovery_nonce: u64,

    /// Number of candidates checked / iterations performed.
    pub checks_performed: u64,

    /// Wall-clock seconds spent on this proof.
    pub elapsed_seconds: f64,

    pub timestamp_utc: String,

    /// Machine's Ed25519 signature over the proof fields (base64).
    /// Verified by `DiscoveryVerifier` before accepting.
    pub machine_signature: String,

    // ── Useful Hash Commitment (BTC-compatible seal) ──────────────────────
    /// Nonce searched until `seal_hash` starts with `seal_difficulty_bits`
    /// zero bits.  Same SHA256 loop as Bitcoin mining.
    pub seal_nonce: u64,

    /// `SHA256(seal_nonce_be8 || output_hash_bytes || challenge_id_bytes)` — hex.
    pub seal_hash: String,

    /// Required leading zero bits in `seal_hash`.  Must meet the challenge's
    /// declared difficulty (which itself must meet the chain's minimum).
    pub seal_difficulty_bits: u32,
}

// ── Seal computation ───────────────────────────────────────────────────────

/// Compute the seal hash for a given nonce, output hash, and challenge ID.
///
/// Formula: `SHA256(seal_nonce_be8 || output_hash_bytes || challenge_id_bytes)`
///
/// The `challenge_id` already embeds the `chain_id` prefix, so cross-chain
/// replay is impossible: the same nonce + output_hash gives a different
/// `seal_hash` on a different chain.
pub fn compute_seal_hash(seal_nonce: u64, output_hash_hex: &str, challenge_id: &str) -> String {
    let output_hash_bytes = hex::decode(output_hash_hex).unwrap_or_default();
    let mut h = Sha256::new();
    h.update(seal_nonce.to_be_bytes());
    h.update(&output_hash_bytes);
    h.update(challenge_id.as_bytes());
    hex::encode(h.finalize())
}

/// Returns `true` when `seal_hash_hex` has at least `difficulty_bits` leading
/// zero *bits*.
pub fn meets_difficulty(seal_hash_hex: &str, difficulty_bits: u32) -> bool {
    if difficulty_bits == 0 { return true; }
    let full_nibbles = (difficulty_bits / 4) as usize;
    let rem_bits     = difficulty_bits % 4;
    let chars: Vec<char> = seal_hash_hex.chars().collect();
    let need = full_nibbles + if rem_bits > 0 { 1 } else { 0 };
    if chars.len() < need { return false; }
    for &c in chars.iter().take(full_nibbles) {
        if c != '0' { return false; }
    }
    if rem_bits > 0 {
        let nibble = u8::from_str_radix(&chars[full_nibbles].to_string(), 16)
            .unwrap_or(0xFF);
        let mask = !((1u8 << (8 - rem_bits)) - 1);
        if (nibble << 4) & mask != 0 { return false; }
    }
    true
}

/// Search for a `seal_nonce` starting at `start` such that
/// `compute_seal_hash(nonce, output_hash, challenge_id)` meets `difficulty_bits`.
///
/// Returns `(nonce, seal_hash_hex)` or `None` if `max_attempts` exhausted.
/// In production use `max_attempts = u64::MAX`; pass a small value in tests.
pub fn find_seal_nonce(
    output_hash_hex: &str,
    challenge_id:    &str,
    difficulty_bits: u32,
    start:           u64,
    max_attempts:    u64,
) -> Option<(u64, String)> {
    for i in 0..max_attempts {
        let nonce = start.wrapping_add(i);
        let hash  = compute_seal_hash(nonce, output_hash_hex, challenge_id);
        if meets_difficulty(&hash, difficulty_bits) {
            return Some((nonce, hash));
        }
    }
    None
}

impl DiscoveryProof {
    /// Verify the seal fields are internally consistent.
    ///
    /// This does NOT check the machine signature (that requires an Ed25519
    /// verifier from the identity layer).  It only confirms:
    ///   1. `seal_hash` == `SHA256(seal_nonce || output_hash || challenge_id)`
    ///   2. `seal_hash` meets `seal_difficulty_bits`
    pub fn verify_seal(&self) -> Result<(), PoCDError> {
        let recomputed = compute_seal_hash(
            self.seal_nonce,
            &self.output_hash,
            &self.challenge_id,
        );
        if recomputed != self.seal_hash {
            return Err(PoCDError::InvalidSeal {
                reason: format!(
                    "seal_hash mismatch: got {}, expected {}",
                    self.seal_hash, recomputed
                ),
            });
        }
        if !meets_difficulty(&self.seal_hash, self.seal_difficulty_bits) {
            return Err(PoCDError::InsufficientDifficulty {
                required: self.seal_difficulty_bits,
                got:      leading_zero_bits(&self.seal_hash),
            });
        }
        Ok(())
    }
}

/// Count the number of leading zero *bits* in a hex-encoded hash.
fn leading_zero_bits(hex: &str) -> u32 {
    let mut count = 0u32;
    for ch in hex.chars() {
        let nibble = u8::from_str_radix(&ch.to_string(), 16).unwrap_or(0xFF);
        if nibble == 0 {
            count += 4;
        } else {
            count += nibble.leading_zeros() - 4; // nibble occupies low 4 bits
            break;
        }
    }
    count
}
