-- Migration 001: research_objectives
--
-- Stores versioned research objectives linked to Grand Challenge IDs.
-- This table is the anchor for all downstream provenance.
--
-- IMPORTANT: This table is NOT the authoritative source for reward eligibility.
-- The blockchain (MicrotaskRegistry / DiscoveryReceipt) independently enforces
-- accepted commitments and double-payment protection.  This table records the
-- research history only.

CREATE TABLE IF NOT EXISTS research_objectives (
    -- Stable objective ID generated by ResearchObjective::make_id().
    -- Format: "{challenge_id}::obj::{slug}"
    objective_id        TEXT        PRIMARY KEY,

    -- Parent Grand Challenge ID (e.g. "qcb-mainnet-1::hash::HASH-001")
    challenge_id        TEXT        NOT NULL,

    -- Human-readable slug (e.g. "sha256-collision-search-v1")
    slug                TEXT        NOT NULL,

    -- Research track (mirrors ChallengeTrack on the challenge)
    track               TEXT        NOT NULL,

    -- Algorithm / experiment version string
    algorithm_version   TEXT        NOT NULL,

    -- Total computational range bounds [range_start, range_end)
    range_start         BIGINT      NOT NULL CHECK (range_start >= 0),
    range_end           BIGINT      NOT NULL CHECK (range_end >= 0),

    -- Preferred workload class for decomposition hints
    workload_class      TEXT        NOT NULL DEFAULT 'cpu',

    -- Objective lifecycle status (mirrors ObjectiveStatus enum)
    -- Values: 'active' | 'completed' | 'cancelled'
    status              TEXT        NOT NULL DEFAULT 'active',

    -- Verification specification (free-form JSON, not consensus-critical)
    verification_spec   JSONB       NOT NULL DEFAULT '{}',

    -- Timestamps
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_research_objectives_challenge
    ON research_objectives (challenge_id);

CREATE INDEX IF NOT EXISTS idx_research_objectives_status
    ON research_objectives (status);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_research_objectives_updated_at
    BEFORE UPDATE ON research_objectives
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
