-- Migration 002: research_tasks
--
-- Stores individual microtasks decomposed from a research_objective.
-- Task IDs are deterministic (format: "{objective_id}::task::{start:016x}-{end:016x}")
-- so they can be regenerated from the objective at any time.

CREATE TABLE IF NOT EXISTS research_tasks (
    -- Deterministic task ID generated by ResearchMicrotask::make_id()
    task_id             TEXT        PRIMARY KEY,

    -- Parent objective (FK to research_objectives)
    objective_id        TEXT        NOT NULL
        REFERENCES research_objectives (objective_id) ON DELETE CASCADE,

    -- Range [range_start, range_end) this task covers — non-overlapping by design
    range_start         BIGINT      NOT NULL CHECK (range_start >= 0),
    range_end           BIGINT      NOT NULL CHECK (range_end   >= 0),

    -- Workload class
    workload_class      TEXT        NOT NULL DEFAULT 'cpu',

    -- Deterministic input seed derived from SHA-256(objective_id || start || end)
    input_seed          BIGINT      NOT NULL,

    -- Task lifecycle status (mirrors MicrotaskStatus enum)
    -- Values: 'available' | 'assigned' | 'submitted' | 'accepted' | 'rejected'
    status              TEXT        NOT NULL DEFAULT 'available',

    -- Miner / worker identity that claimed this task (set on assign)
    assigned_to         TEXT,

    -- DiscoveryReceipt ID that settled this task (set on accept)
    settled_receipt_id  TEXT,

    -- Timestamps
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_research_tasks_objective
    ON research_tasks (objective_id);

CREATE INDEX IF NOT EXISTS idx_research_tasks_status
    ON research_tasks (status);

CREATE INDEX IF NOT EXISTS idx_research_tasks_assigned_to
    ON research_tasks (assigned_to)
    WHERE assigned_to IS NOT NULL;

CREATE TRIGGER trg_research_tasks_updated_at
    BEFORE UPDATE ON research_tasks
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
