-- Migration 005: research_findings
--
-- Records research findings — including NEGATIVE findings.
-- The QCB Discovery Engine analyses ALL accepted microtask results,
-- not only results labelled as discoveries.  Negative findings are
-- scientifically valuable: they narrow the search space and prevent
-- future miners from duplicating already-explored territory.
--
-- A finding is created by the QDE analysis layer (Change Set G).
-- It is NOT created by the chain or by miners directly.

CREATE TABLE IF NOT EXISTS research_findings (
    -- UUID primary key
    finding_id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Parent objective
    objective_id        TEXT        NOT NULL
        REFERENCES research_objectives (objective_id) ON DELETE CASCADE,

    -- Specific task that produced the evidence (may be NULL for
    -- aggregate findings spanning multiple tasks)
    task_id             TEXT
        REFERENCES research_tasks (task_id) ON DELETE SET NULL,

    -- Finding classification
    -- Values: 'positive_discovery' | 'negative_finding' | 'anomaly' |
    --         'boundary_refinement' | 'inconclusive'
    finding_type        TEXT        NOT NULL,

    -- Human-readable summary (generated by QDE)
    summary             TEXT        NOT NULL,

    -- Confidence level [0.0, 1.0]  (NULL = unscored)
    confidence          NUMERIC(5,4)
        CHECK (confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)),

    -- Supporting evidence (list of result_ids, verification_ids, or artifact_ids)
    evidence_refs       JSONB       NOT NULL DEFAULT '[]',

    -- Whether this finding has been incorporated into the objective's
    -- active search range (e.g. a boundary refinement narrowing range_start/range_end)
    applied_to_objective    BOOLEAN NOT NULL DEFAULT FALSE,

    -- Timestamps
    found_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_research_findings_objective
    ON research_findings (objective_id);

CREATE INDEX IF NOT EXISTS idx_research_findings_type
    ON research_findings (finding_type);

CREATE INDEX IF NOT EXISTS idx_research_findings_task
    ON research_findings (task_id)
    WHERE task_id IS NOT NULL;

CREATE TRIGGER trg_research_findings_updated_at
    BEFORE UPDATE ON research_findings
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
